/*
 ******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2019-08-27

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

 ******************************************************************************
 */

#include "main.h"

/* Private functions */
void system_init(void){
	//	DWT_Init();
	DWT_Delay_Init();
	MQTT_Init();
	Led_Init();
	Uart_Init(USART_2,9600);
	Uart_Putstring(USART_2,"System Started ...\n");
	MQTT_State = MQTT_DISCONNECTED;
	WIFI_State = WIFI_DISCONNECTED;
}

void T_Monitor(void* pvData){
	EventBits_t	ebValues;
	Uart_Putstring(USART_2,"T_Monitor ...\n");
	INT32U temp = 20;
	INT8U humStr[5] = {0};
	INT8U tempStr[5] = {0};
	INT8U I_RH=70,D_RH,I_Temp=80,D_Temp,CheckSum;

	while(1){
		ebValues = xEventGroupWaitBits(egEvents,(E_MQTT_CONNECTED),0,0,portMAX_DELAY);

		if(ebValues&E_MQTT_CONNECTED){

			Request();
			Response();
			I_RH=Receive_data();
			D_RH=Receive_data();
			I_Temp=Receive_data();
			D_Temp=Receive_data();
			CheckSum=Receive_data();

			if ((I_RH + D_RH + I_Temp + D_Temp) != CheckSum)
			{
				MQTT_Publish("OMR","ERROR",strlen("ERROR"),0);
			}
			else
			{
				MQTT_Init();
				vTaskDelay(2*TICKS_IN_SECOND);

				sprintf(humStr,"%d",I_RH);
				MQTT_Publish("OMR/Humid",humStr, strlen(humStr),0);
				Uart_Putstring(USART_2,humStr);

				vTaskDelay(1*TICKS_IN_SECOND);

				sprintf(tempStr,"%d",I_Temp);
				MQTT_Publish("OMR/Temp",tempStr,strlen(tempStr),0);
				Uart_Putstring(USART_2,tempStr);

				vTaskDelay(2*TICKS_IN_SECOND);

			}



			Led_On();

		}
	}
}
void T_Control(void* pvData){
	EventBits_t	ebValues;
	Uart_Putstring(USART_2,"T_Control ...\n");
	while(1){
		ebValues = xEventGroupWaitBits(egEvents,(E_CONTROL_ON|E_CONTROL_OFF),1,0,portMAX_DELAY);
		if(ebValues&(E_CONTROL_ON)){
			Led_On();
		}
		else if(ebValues&(E_CONTROL_OFF)){
			Led_Off();
		}
	}
}
void T_Connect(void* pvData){
	EventBits_t	ebValues;
	Uart_Putstring(USART_2,"T_Connect ...\n");
	while(1){
		if(xSemaphoreTake(bsDisconnectedEvent,portMAX_DELAY)){
			Uart_Putstring(WIFI_UART,"ATE0\r\n");
			ebValues = xEventGroupWaitBits(egEvents,E_WIFI_OK,1,1,1*TICKS_IN_SECOND);
			if(ebValues&E_WIFI_OK){
				Uart_Putstring(USART_2,"Echo Done\n");
				vTaskDelay(1*TICKS_IN_SECOND);
				//				Uart_Putstring(WIFI_UART,"AT+CWJAP=\"Aboseif\",\"aboseif14\"\r\n");
				//				Uart_Putstring(WIFI_UART,"AT+CWJAP=\"Arafa\",\"01018180151\"\r\n");
				Uart_Putstring(WIFI_UART,"AT+CWJAP=\"OMRTarek\",\"omeromer\"\r\n");
				ebValues = xEventGroupWaitBits(egEvents,E_WIFI_OK,1,1,20*TICKS_IN_SECOND);
				if(ebValues&E_WIFI_OK){
					Uart_Putstring(USART_2,"WIFI Done\n");
					vTaskDelay(1*TICKS_IN_SECOND);
					Uart_Putstring(WIFI_UART,"AT+CIPSTART=\"TCP\",\"broker.hivemq.com\",1883\r\n");
					ebValues = xEventGroupWaitBits(egEvents,E_WIFI_OK,1,1,7*TICKS_IN_SECOND);
					if(ebValues&E_WIFI_OK){
						Uart_Putstring(USART_2,"TCP Done\n");
						vTaskDelay(500*TICKS_IN_MILLISECOND);
						MQTT_Connect("ID00");
						ebValues = xEventGroupWaitBits(egEvents,E_MQTT_CONNACK,1,1,2*TICKS_IN_SECOND);
						if(ebValues&E_MQTT_CONNACK){
							Uart_Putstring(USART_2,"MQTT Connect Done\n");
							vTaskDelay(1*TICKS_IN_SECOND);
							MQTT_Subscribe("OMR");
							vTaskDelay(1*TICKS_IN_SECOND);
							MQTT_Subscribe("Temp");
							ebValues = xEventGroupWaitBits(egEvents,E_MQTT_SUBACK,1,1,2*TICKS_IN_SECOND);
							if(ebValues&E_MQTT_SUBACK){
								Uart_Putstring(USART_2,"MQTT Subscribe Done\n");
								vTaskDelay(2*TICKS_IN_SECOND);
								xEventGroupSetBits(egEvents,E_MQTT_CONNECTED);
								//MQTT_Publish("OMR","OOO",16,0);
								//Uart_Putstring(USART_2,"MQTT Pub Done\n");
								//vTaskDelay(2*TICKS_IN_SECOND);
							}else{
								xSemaphoreGive(bsDisconnectedEvent);
							}
						}else{
							xSemaphoreGive(bsDisconnectedEvent);
						}
					}else{
						xSemaphoreGive(bsDisconnectedEvent);
					}
				}else{
					xSemaphoreGive(bsDisconnectedEvent);
				}
			}else{
				xSemaphoreGive(bsDisconnectedEvent);
			}

		}
	}
}
void T_WIFIResHandle(void* pvData){
	INT8U msgBuffer[80] = {0};
	INT8U msgBufferInd = 0;
	INT8U msgStartInd = 0;
	INT8U msgLen = 0;
	INT8U packetType = 0;
	INT8U i = 0;
	Uart_Putstring(USART_2,"T_WIFIResHandle ...\n");
	while(1){
		if(xQueueReceive(mqWIFIResp,msgBuffer,portMAX_DELAY)){
			/* Print the message */
			/*for(i = 0; i<msgBuffer[80-1]; i++){
				Uart_Putchar(USART_2,msgBuffer[i]);
			}*/
			packetType = msgBuffer[0];
			switch (packetType) {
			case 0x30:	/* Publish packet was received */
				MQTT_GetMsg(msgBuffer,&msgStartInd,&msgLen);
				if(msgBuffer[msgStartInd] == 'O' && msgBuffer[msgStartInd+1] == 'N'){
					xEventGroupSetBits(egEvents,E_CONTROL_ON);

				}
				else if(msgBuffer[msgStartInd] == 'O' && msgBuffer[msgStartInd+1] == 'F' && msgBuffer[msgStartInd+2] == 'F'){
					xEventGroupSetBits(egEvents,E_CONTROL_OFF);
				}
				break;
			case 0x20:
				xEventGroupSetBits(egEvents,E_MQTT_CONNACK);
				break;
			case 0x90:
				xEventGroupSetBits(egEvents,E_MQTT_SUBACK);
				break;
			case 0x40:
				xEventGroupSetBits(egEvents,E_MQTT_PUBACK);
				break;
			default:
				if(msgBuffer[0] == 'O' && msgBuffer[1] == 'K'){
					xEventGroupSetBits(egEvents,E_WIFI_OK);
				}
				break;
			}
			if(msgBuffer[0] == 0x30){ /* qos = 0 */

			}
		}
	}
}

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
int main(void)
{
	system_init();

	vSemaphoreCreateBinary(bsDisconnectedEvent);
	//
	mxWIFIRes 			= 	xSemaphoreCreateMutex();
	mqWIFIResp 			=  	xQueueCreate(5,80);
	egEvents			=	xEventGroupCreate();

	//	xTaskCreate(T_Monitor,NULL,100,NULL,5,NULL);
	xTaskCreate(T_Monitor,NULL,100,NULL,4,NULL);
	xTaskCreate(T_Control,NULL,100,NULL,2,NULL);
	xTaskCreate(T_Connect,NULL,100,NULL,3,NULL);
	xTaskCreate(T_WIFIResHandle,NULL,125,NULL,1,NULL);

	vTaskStartScheduler();
}
